
   
   
spring:
    application:     name: CUSTOMER    data:
         mongodb:           uri: mongodb://localhost:27017/CUSTOMER                 # security:       #   user: .        #   password: 123
